Serving HTTP on 0.0.0.0 port 4999 ...
10.129.6.52 - - [06/Feb/2020 10:42:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:48] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:49] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:53] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:53] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:53] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:42:53] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [06/Feb/2020 10:44:02] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:44:02] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:44:05] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:44:05] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:44:05] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:44:05] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [06/Feb/2020 10:49:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:49:27] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:49:30] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:49:30] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:49:30] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:49:30] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [06/Feb/2020 10:50:23] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:50:23] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:50:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:50:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:50:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:50:26] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [06/Feb/2020 10:56:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:56:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:56:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:56:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:56:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:56:58] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [06/Feb/2020 10:59:43] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:59:43] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:59:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:59:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:59:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [06/Feb/2020 10:59:46] "GET /setup.in HTTP/1.1" 200 -
